[connections.postgres]
#host = "dbcourse.cs.aalto.fi"
#port = 5432
#dbname = "grp02db_2023"
#user = "grp02_2023"
#password = "A88z1c6B"
url = "postgresql://grp02_2023:A88z1c6B@dbcourse.cs.aalto.fi:5432/grp02db_2023"